Page({
  data:{
    banner:['../../images/index2.jpg','../../images/index3.webp','../../images/index4.webp'],
    indexConfig:[
      {
        icon:'../../images/index/index1.png',
        text:'快递代取'
      },
      {
        icon:'../../images/index/index2.png',
        text:'打印服务'
      },
      {
        icon:'../../images/index/index3.png',
        text:'校园跑腿'
      },
      {
        icon:'../../images/index/inde4.png',
        text:'快递代取'
      },
      {
        icon:'../../images/index/index5.png',
        text:'租借服务'
      },
      {
        icon:'../../images/index/index6.png',
        text:'游戏陪玩'
      },
      {
        icon:'../../images/index/index7.png',
        text:'帮我送'
      },
      {
        icon:'../../images/index/index8.png',
        text:'代替服务'
      },
      {
        icon:'../../images/index/index9.png',
        text:'其他帮取'
      },
    ]
  },
  hand(){
    wx.showModal({
      title:'公告',
      content:'关注工作号可享订单推送，接单员请务必添加客服v:18236335490'
    })
  }
});
